version: '2'

services:

  php-fpm:
    build: ./php-fpm
    volumes:
      - ../src:/var/www
    expose:
      - "9000"
    environment:
      HTTP_SERVER: ${HTTP_SERVER}
      HTTPS_SERVER: ${HTTPS_SERVER}
      MYSQL_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: 3306

  apache:
    build: ./apache
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./apache/sites:/etc/apache2/sites-available
      - ../src:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ../data/init-backup.sql.dummy:/docker-entrypoint-initdb.d/init-backup.sql
      - ../data/database/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
